/**
 * Client facade tests.
 *
 * Exercises the unified `Client` surface (`client.auth` / `client.storage` /
 * `client.message`) and the shared HTTP credential plumbing: construction,
 * header injection, the register round-trip, session restore, and logout.
 *
 * Nothing here is faked below the wire. Identity derivation + the Poseidon
 * commitment are real (circomlibjs), the OPRF stub answers with a real
 * ristretto255 blinded evaluation (src/auth/oprf.ts), and the ZK login proof
 * is genuinely generated by snarkjs — a devDependency here — against the
 * checked-in `circuits/build/` artifacts. Only `fetch` is stubbed, so the
 * register flow's full request sequence is asserted end to end and offline.
 *
 * Note: in Node, snarkjs hands a circuit path straight to fastfile, which
 * reads a plain string as a FILESYSTEM PATH. The `circuits` option below must
 * therefore be absolute local paths, not the client's default http:// URLs.
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { fileURLToPath } from 'node:url';
import { Client, DEFAULT_BASE_URL } from '../../src/core/Client';
import { MemorySessionStore } from '../../src/core/Session';
import { oprfBlindEvaluate, oprfDeriveKey } from '../../src/auth/oprf';

const BASE_URL = 'http://localhost:8787';
const API_KEY = 'mk_test_pk_0123456789abcdef0123456789abcdef';

/** Local proving artifacts — snarkjs reads these off disk, so the ZK proof
 *  runs hermetically with no network and no accelerator. */
const CIRCUITS = {
    wasmUrl: fileURLToPath(new URL('../../circuits/build/preimagePoK_js/preimagePoK.wasm', import.meta.url)),
    zkeyUrl: fileURLToPath(new URL('../../circuits/build/preimagePoK_0001.zkey', import.meta.url)),
};

/** Stand-in for the accelerator's OPRF secret. Fixed so runs are deterministic. */
const OPRF_SERVER_KEY = oprfDeriveKey(new Uint8Array(32).fill(7));

/** Records every request and returns canned JSON responses keyed by path. */
function makeFetch(routes: Record<string, (body: any) => { status?: number; json: any }>) {
    const calls: Array<{ url: string; method: string; headers: Headers; body: any }> = [];
    const fetchFn = (async (input: any, init: any) => {
        const url = typeof input === 'string' ? input : input.url;
        const headers = new Headers(init?.headers);
        const body = init?.body ? JSON.parse(init.body) : undefined;
        calls.push({ url, method: init?.method ?? 'GET', headers, body });

        const match = Object.keys(routes).find((p) => url.endsWith(p));
        if (!match) return new Response('not found', { status: 404 });
        const { status = 200, json } = routes[match](body);
        return new Response(JSON.stringify(json), {
            status,
            headers: { 'Content-Type': 'application/json' },
        });
    }) as unknown as typeof fetch;

    return { fetchFn, calls };
}

describe('Client — construction', () => {
    it('defaults baseUrl and apiKey when omitted', () => {
        // Both optional: baseUrl falls back to the hosted Accelerator, and
        // auth + storage work without an app key during the migration.
        const client = new Client();
        expect(client.baseUrl).toBe(DEFAULT_BASE_URL);

        // An explicit baseUrl overrides the default.
        expect(new Client({ baseUrl: BASE_URL }).baseUrl).toBe(BASE_URL);
    });

    it('exposes auth / storage / message namespaces', () => {
        const client = new Client({ apiKey: API_KEY, baseUrl: BASE_URL });
        expect(client.auth).toBeDefined();
        expect(client.auth.zk).toBeDefined();
        expect(client.kv).toBeDefined();
        expect(client.storage).toBeDefined();
        expect(client.message).toBeDefined();
        expect(client.isAuthenticated).toBe(false);
        expect(client.user).toBeNull();
    });

    it('strips a trailing slash from baseUrl', () => {
        const client = new Client({ apiKey: API_KEY, baseUrl: BASE_URL + '/' });
        expect(client.baseUrl).toBe(BASE_URL);
    });
});

describe('Client — credential injection', () => {
    it('stamps the app key on auth requests', async () => {
        // M1.0 register() is a five-call flow: register the commitment, sign in
        // with the in-memory random-seed identity (challenge → proof →
        // authenticate) to get a token, then enroll the OPRF-gated password
        // factor so the seed is recoverable on the next login. Every leg is
        // stubbed for real — an unstubbed one 404s and the flow throws.
        const { fetchFn, calls } = makeFetch({
            '/api/auth/zk-register': () => ({ json: { success: true } }),
            '/api/auth/challenge': () => ({
                json: {
                    challengeId: 'chal-1',
                    // 32 bytes of hex; generateAuthProof reduces it into the field.
                    nonce: 'a'.repeat(64),
                    commitment: '0',
                },
            }),
            '/api/auth/zk-authenticate': () => ({ json: { token: 'sess-tok-new', username: 'alice' } }),
            // A real ristretto255 blinded evaluation — oprfFinalize decodes the
            // point, so a placeholder value would throw.
            '/api/auth/oprf': (body: any) => ({
                json: {
                    evaluated: Buffer.from(
                        oprfBlindEvaluate(OPRF_SERVER_KEY, new Uint8Array(Buffer.from(body.blinded, 'base64'))),
                    ).toString('base64'),
                },
            }),
            '/api/auth/vault/factor': () => ({ json: { ok: true, id: 'password' } }),
        });
        const client = new Client({
            apiKey: API_KEY,
            baseUrl: BASE_URL,
            fetch: fetchFn,
            circuits: CIRCUITS,
        });

        await client.auth.zk.register({ username: 'alice', password: 'hunter2-correct', login: false });

        const reg = calls.find((c) => c.url.endsWith('/api/auth/zk-register'))!;
        expect(reg).toBeDefined();
        expect(reg.method).toBe('POST');
        expect(reg.headers.get('X-Muhkoo-Key')).toBe(API_KEY);
        // No session yet → no session header.
        expect(reg.headers.get('X-Muhkoo-Session')).toBeNull();
        // Real derivation produced a decimal-string commitment + base64 keys.
        expect(reg.body.username).toBe('alice');
        expect(reg.body.commitment).toMatch(/^[0-9]+$/);
        expect(typeof reg.body.ecdhPublicKey).toBe('string');
        expect(typeof reg.body.ecdsaPublicKey).toBe('string');

        // Pin the whole sequence: this is the regression net for the vault flow.
        expect(calls.map((c) => new URL(c.url).pathname)).toEqual([
            '/api/auth/zk-register',
            '/api/auth/challenge',
            '/api/auth/zk-authenticate',
            '/api/auth/oprf',
            '/api/auth/vault/factor',
        ]);
        expect(calls[4].method).toBe('PUT');

        // Every OPRF request declares the RFC 9497 mode this client speaks, so a
        // server can refuse rather than answer in a mode we did not ask for. This
        // is the only end-to-end path in the suite that exercises the real
        // request body, so it is where the field is worth pinning.
        expect(calls[3].body.oprfProtocol).toBe(0);

        // `login: false` signs the freshly registered user back out (locally).
        expect(client.isAuthenticated).toBe(false);
    }, 30000);

    it('stamps the session token on requests once a session exists', async () => {
        const store = new MemorySessionStore();
        store.save({ token: 'sess-tok-123', username: 'bob', commitment: '42' });

        const { fetchFn, calls } = makeFetch({
            '/api/auth/verify': () => ({ json: { username: 'bob' } }),
        });
        const client = new Client({
            apiKey: API_KEY,
            baseUrl: BASE_URL,
            fetch: fetchFn,
            sessionStore: store,
        });

        const user = await client.auth.zk.restore();
        expect(user).toEqual({ username: 'bob', commitment: '42' });
        expect(client.isAuthenticated).toBe(true);

        const verify = calls.find((c) => c.url.endsWith('/api/auth/verify'))!;
        expect(verify.headers.get('X-Muhkoo-Key')).toBe(API_KEY);
        expect(verify.headers.get('X-Muhkoo-Session')).toBe('sess-tok-123');
    });
});

describe('Client — session lifecycle', () => {
    it('restore() drops a stale token when verify fails', async () => {
        const store = new MemorySessionStore();
        store.save({ token: 'stale', username: 'carol', commitment: '7' });

        const { fetchFn } = makeFetch({
            '/api/auth/verify': () => ({ status: 401, json: { error: 'expired' } }),
        });
        const client = new Client({ apiKey: API_KEY, baseUrl: BASE_URL, fetch: fetchFn, sessionStore: store });

        const user = await client.auth.zk.restore();
        expect(user).toBeNull();
        expect(client.isAuthenticated).toBe(false);
        expect(store.load()).toBeNull();
    });

    it('logout() clears session state', async () => {
        const store = new MemorySessionStore();
        store.save({ token: 't', username: 'dave', commitment: '9' });
        const { fetchFn } = makeFetch({ '/api/auth/verify': () => ({ json: { username: 'dave' } }) });
        const client = new Client({ apiKey: API_KEY, baseUrl: BASE_URL, fetch: fetchFn, sessionStore: store });

        await client.auth.zk.restore();
        expect(client.isAuthenticated).toBe(true);
        await client.auth.zk.logout();
        expect(client.isAuthenticated).toBe(false);
        expect(store.load()).toBeNull();
    });
});

describe('Client — namespaces pending implementation', () => {
    let client: Client;
    beforeEach(() => {
        client = new Client({ apiKey: API_KEY, baseUrl: BASE_URL });
    });

    it('kv methods refuse to run unauthenticated', async () => {
        // Encrypted write needs identity; read needs at least a session.
        await expect(client.kv.set('todos', '1', {})).rejects.toThrow(/identity/);
        await expect(client.kv.get('todos', '1')).rejects.toThrow(/not signed in/);
    });

    it('message send refuses to run unauthenticated', async () => {
        await expect(client.message.send('user:abc', { text: 'hi' })).rejects.toThrow(/not signed in/);
    });

    it('message send rejects a non-user target', async () => {
        // Even before auth, the target-shape guard for send() is meaningful.
        await expect(client.message.send('todos', { text: 'hi' })).rejects.toThrow(/user:/);
    });
});
